---
title: "Relatório Descritivo"
author: "Flavia de Jesus e Micaely Mendes"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r, include=FALSE}
library(tidyverse)
dados <- readxl::read_xlsx("flavia.xlsx")
```

```{r, include=FALSE}
dados <- dados %>%
  rename(c("menor1" = "menor que 1", "um_quatro" = "1-4 anos", "cinco_nove" = "5-9 anos",
           "dez_quatorze" = "10-14 anos", "quinze_dezenove" = "15-19 anos", 
           "regiao" = "Macrorregião de Saúde"))
```

```{r, echo=FALSE, message=FALSE}
head(dados)
```

```{r, echo=FALSE}
idade <- dados %>%
  group_by(menor1, um_quatro, cinco_nove, dez_quatorze, quinze_dezenove) %>%
  gather("menor1", "um_quatro", "cinco_nove", "dez_quatorze", "quinze_dezenove",
         key = "idade", value = "casos") 

idade_casos <- idade %>%
  group_by(idade, casos) %>%
  summarise(
    n = n()
  )

ggplot(idade_casos, aes(x=idade)) +
  geom_bar()
```


```{r, include=FALSE}
anos_casos <- data.frame(Anos = c("1996-2000", "2001-2005", "2006-2010", "2011-2015", "2016-2020"),
                         Casos = c(4763,4901,4851,4627,4188),
                         stringsAsFactor=FALSE)
```


```{r, echo=FALSE}
ggplot(anos_casos, aes(x=Anos, y=Casos)) +
  geom_bar(stat = "identity") +
  theme_minimal() +
  geom_text(aes(label = Casos, vjust = -0.5)) +
  scale_y_continuous(
    limits = c(0, 6000),
    breaks = seq(0, 6000, 500)
  ) +
  scale_fill_continuous()
```











